### ISSUE TITLE
no 3d annotation in dataset

### ISSUE THREAD

**Issue by alihahaa** [TRI-ML/dgp#13]
Hi, thanks for your greate work!

I found that there is no 3d annotation in the dataset, did i miss someting?

**Comment by quincy-kh-chen** [comment]
Currently, we have BOUNDING_BOX_3D defined in the [proto schema](https://github.com/TRI-ML/dgp/blob/master/dgp/proto/annotations.proto#L27) and [structure utilities](https://github.com/TRI-ML/dgp/blob/6ff13df792ac210a7b4e3c2f11c57079ac9c884a/dgp/utils/structures/bounding_box_3d.py). Also have placeholders for SEMANTIC_SEGMENTATION_3D, INSTANCE_SEGMENTATION_3D, etc defined in [AnnotationType](https://github.com/TRI-ML/dgp/blob/6ff13df792ac210a7b4e3c2f11c57079ac9c884a/dgp/proto/annotations.proto#L33)
