### ISSUE TITLE
DGP Proto: Which Ontology message to be used?

### ISSUE THREAD

**Issue by pd-nisse** [TRI-ML/dgp#35]
Currently there are two places with Ontology messages:

1. https://github.com/TRI-ML/dgp/blob/80e387737d82b1474fdf7971f28a8fbbf66816a7/dgp/proto/dataset.proto#L18
2. https://github.com/TRI-ML/dgp/blob/80e387737d82b1474fdf7971f28a8fbbf66816a7/dgp/proto/ontology.proto#L42

Could you confirm which is the one to be used in DGP 1.0 release implementation? Thank you!

**Comment by quincy-kh-chen** [comment]
Hello @pd-nisse,

Please use `dgp/dgp/proto/ontology.proto`
https://github.com/TRI-ML/dgp/blob/80e387737d82b1474fdf7971f28a8fbbf66816a7/dgp/proto/ontology.proto#L42

`Ontology ` in dgp/dgp/proto/dataset.proto is a deprecated message. We keep this deprecated message for some old datasets. Will remove it soon once all old Ontology got upgraded to `dgp/dgp/proto/ontology.proto`
